import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data)
plt.plot(df['Date'], df['Sales'], label='Sales')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.title('Sales Over Time')
plt.legend()
plt.show()
plt.scatter(df['Quantity'], df['Revenue'])
plt.xlabel('Quantity')
plt.ylabel('Revenue')
plt.title('Scatter Plot of Quantity vs Revenue')
plt.show()
plt.bar(df['Category'], df['Profit'])
plt.xlabel('Category')
plt.ylabel('Profit')
plt.title('Bar Plot of Profit by Category')
plt.show()
plt.hist(df['Price'], bins=20, color='skyblue', edgecolor='black')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Histogram of Price Distribution')
plt.show()
plt.boxplot(df['Sales'], vert=False)
plt.xlabel('Sales')
plt.title('Box Plot of Sales')
plt.show()
sns.lineplot(x='Date', y='Sales', data=df, label='Sales')
plt.title('Seaborn Line Plot of Sales Over Time')
plt.show()
sns.scatterplot(x='Quantity', y='Revenue', data=df)
plt.title('Seaborn Scatter Plot of Quantity vs Revenue')
plt.show()
sns.barplot(x='Category', y='Profit', data=df)
plt.title('Seaborn Bar Plot of Profit by Category')
plt.show()
sns.histplot(df['Price'], bins=20, kde=True, color='skyblue')
plt.title('Seaborn Histogram of Price Distribution')
plt.show()
sns.boxplot(x='Sales', data=df)
plt.title('Seaborn Box Plot of Sales')
plt.show()
